setwd("C:/Users/VSharma/Desktop/R files")



## ******Function for generating plots from the final report ********************

createReport<-function(Finalreport) {
  library(dplyr)
  library(ggplot2)
  library(scales)
  Finalreport<-read.csv("FinalV2.csv",stringsAsFactors = FALSE)
  Piereport<-read.csv("Piereport.csv",stringsAsFactors = FALSE)
 
  # ******Summarizing the report for Revenue generated by each Customer type annually******** 
  
  Report1<-Finalreport%>%
    group_by(Customer.Type)%>%
    summarise(totalrev=sum(monthlyrev/1000))
  
  #************ Generating annual revenue plot for different customer types********
  
  x<-ggplot(Report1,aes(x=Customer.Type,y=totalrev,fill=Region))+ 
    geom_bar(stat = "identity",width=0.3, fill="light blue",colour="black",size=0.25)+  
    theme(text = element_text(size=15), axis.text.x = element_text(angle=90, vjust=1)) + 
    labs(x="Types of Customers",y="Revenue")+ theme(axis.title.x=element_text(face="italic",size=14)
    ,axis.title.y=element_text(angle=90,face="italic",size = 14))+theme(plot.background = element_blank())+
    theme(axis.line.x = element_line(color="black", size = 2),
     axis.line.y = element_line(color="black", size = 2)) +scale_y_continuous(labels = comma)
  
  #**********************Summarizing the report for Revenue generated by each enterprise annually*****************************************************************
  
  
  Report2<-Finalreport%>%
    group_by(Enterprise)%>%
    summarise(totalrev=sum(monthlyrev/1000))
  
  
#************ Generating the plot for the annual revenue by different types of Enterptris types.
  
  y<-ggplot(Report2,aes(x=Enterprise,y=totalrev,fill=Region))+ 
  geom_bar(stat = "identity",width=0.2,fill="light yellow",colour="black")+  
  theme(text = element_text(size=15),axis.text.x = element_text(angle=360, vjust=1))+
  labs(x="Enterprise type",y="Revenue")+ theme(axis.title.x=element_text(face="italic",size=14)
 ,axis.title.y=element_text(angle=90,face="italic",size = 14))+theme(plot.background = element_blank())+
  theme(axis.line.x = element_line(color="black", size = 2),axis.line.y = element_line(color="black", size = 2))
  +scale_y_continuous(labels = comma)
  
  #***********************************************************************************************
  
  print(x)
  print(y)
  
}


